Beginning
Praddby/LearningLanguageWithFlashcards pull request #2
Opened 2018-07-11 18:40 UTC by Praddby

2018-07-17 09:30 UTC, dragg requested changes

2018-07-17 09:30 UTC, dragg commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        return CardGroup::with('standardCards')->where('is_standard', true)->get();
Логику работы с полями лучше инкапсулировать в модель, так как она именно отвечает за работу с модификацией их. То есть должно было быть здесь что-то
`return CardGroup::with('standardCards')->standardCards()->get();`

2018-07-17 09:30 UTC, dragg commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        $cardGroup->is_standard = true;
То же самое, что и выше. Лучше `$cardGroup->markStandard()` или `$cardGroup->setStandard()` или наподобии, но думаю идею ты понял.

2018-07-17 09:30 UTC, dragg commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        return CardGroup::with('standardCards')->find($cardGroup->id);
Почему просто не вернешь $cardGroup?

2018-07-17 09:30 UTC, dragg commented on database/migrations/2018_05_28_130449_create_card_groups_table.php
> +        Schema::table('card_groups', function (Blueprint $table) {
Мы же вроде разговаривали, что удаление связи не нужно, когда мы дропим саму таблицу.

2018-07-17 09:30 UTC, dragg commented on database/migrations/2018_07_12_155259_create_user_cards_table.php
> +        Schema::table('user_cards', function (Blueprint $table) {
То же, что и выше по миграции.

2018-07-17 09:30 UTC, dragg commented on database/migrations/2018_07_12_160222_create_level_cards_table.php
> +        Schema::create('level_cards', function (Blueprint $table) {
Что-то у тебя много очень похожих таблиц и моделей. Надо бы нам разобраться, что и зачем нам надо. Попробуй подготовить описание того, что именно ты делаешь и как это видишь и мы обсудим, действительно тебе это именно так нужно.

2018-07-17 09:30 UTC, dragg commented on database/seeds/StandardCardsSeeder.php
> +                'name_original'    => str_random(10),
Можно что-то хоть на текст создать с помощью фейкра (https://github.com/fzaninotto/Faker).

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/app.js
> +Vue.component('nav-component', require('./components/admin/NavComponent.vue').default);
Мне понравилась идея из code style по vuejs - https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended. А именно где указывается, что на единственные компоненты на странице стоит указывать через 'the'. Например, в твоей случае 'the-nav-bar'. И не знаю как я не замечал до этого, но слово 'component' в конце вообще ужастно смотрится и ни капли не информативно. Лучше использовать что-то типо 'users-lists', 'user-form' и тп

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/components/admin/CardsComponent.vue
> +      <a href="#" class="btn btn-primary mb-4 ml-4" data-toggle="modal" data-target="#addCardModal" data-backdrop="static">Добавить картоку</a>
Строки не должны превышать 120 символов! А еще лучше 80.
Такие стандарты идут еще давно, но до сих пор сохраняются, потому что это удобно для чтения кода, почти все редакторы делают такую пометку, когда текст вылазиет и в том же гитхабе (да и уверен в битбакете) не помещается и приходиться скроллить, что не удобно.

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/components/admin/CardsComponent.vue
> +        this.isEditing = '';
Почему пустая строка? Почему не null?

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/components/admin/CardsComponent.vue
> +        let idx = this.cards.indexOf(card);
Что за название переменно? Предложишь еще варианты? Да и зачем это делать здесь? Если в случае ошибки эта переменная нигде использоваться не будет.

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/components/modals/ModalAddCardComponent.vue
> +            console.log(data);
Убирай такое.

2018-07-17 09:30 UTC, dragg commented on resources/assets/js/components/modals/ModalAddCardComponent.vue
> +        axios.post('/standard_cards/', { cards: this.cards, name_category: this.name_category })
Зачем оканчивающий слеш в запросе?

2018-07-17 09:30 UTC, dragg commented on routes/web.php
> +    Route::apiResource('standard_cards', 'Admin\StandardCardsController')->only(['index', 'store', 'update', 'destroy']);
Тебе не надоедло каждый раз писать 'Admin\' в неймспейсе к контроллеру? Может найдешь чутка лучше способ?

2018-07-17 09:55 UTC, Praddby commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        return CardGroup::with('standardCards')->find($cardGroup->id);
Я тоже так думал, но $cardGroup вернется без данных из таблицы "standardCards". Поэтому выкрутился так: CardGroup::with('standardCards') .......

2018-07-17 13:34 UTC, dragg commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        return CardGroup::with('standardCards')->find($cardGroup->id);
Тогда нужно было сделать так `return $cardGroup->fresh('standardCards')`;

2018-07-17 16:17 UTC, Praddby commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        return CardGroup::with('standardCards')->find($cardGroup->id);
Спасибо, я не знал про fresh().

2018-07-17 16:19 UTC, Praddby commented on app/Http/Controllers/Admin/StandardCardsController.php
> +        $cardGroup->is_standard = true;
А думал зачем этот scope ))))) Исправил

2018-07-17 17:00 UTC, Praddby commented on resources/assets/js/components/admin/CardsComponent.vue
> +        this.isEditing = '';
Привычка ... а лучше null  использовать?

2018-07-17 17:04 UTC, Praddby commented on resources/assets/js/components/admin/CardsComponent.vue
> +        let idx = this.cards.indexOf(card);
Ты прав, перенес в блок then, название оставил тоже самое ))) (это типа индекс сокращено).. да и используется сразу, думаю понятно будет)

2018-07-17 17:05 UTC, Praddby commented on resources/assets/js/components/modals/ModalAddCardComponent.vue
> +            console.log(data);
Ок

2018-07-17 17:06 UTC, Praddby commented on resources/assets/js/components/modals/ModalAddCardComponent.vue
> +        axios.post('/standard_cards/', { cards: this.cards, name_category: this.name_category })
Не нужен. Убрал.

2018-07-17 17:16 UTC, Praddby commented on routes/web.php
> +    Route::apiResource('standard_cards', 'Admin\StandardCardsController')->only(['index', 'store', 'update', 'destroy']);
Хорошая мысль. Переделал)

2018-07-19 09:34 UTC, Praddby commented on database/migrations/2018_05_28_130449_create_card_groups_table.php
> +        Schema::table('card_groups', function (Blueprint $table) {
Убрал лишнее

2018-07-19 10:02 UTC, dragg commented on resources/assets/js/components/admin/CardsComponent.vue
> +        this.isEditing = '';
Да, лучше null потому что это позволяет нам знать, что значение именно нулевое/очищено, а не гадать почему тут пустая строка и имеет это какой-нибудь "скрытый" смысл или нет.

2018-07-19 10:19 UTC, merged

2018-07-19 11:03 UTC, dragg commented on database/seeds/StandardCardsSeeder.php
> +                'name_original'    => str_random(10),
Что на счет этого? Давай попробуй использовать фейкер - он понадобиться еще не раз в твоей практике.

2018-07-19 11:03 UTC, dragg commented on resources/assets/js/app.js
> +Vue.component('nav-component', require('./components/admin/NavComponent.vue').default);
И этот пункт ты что-то совсем пропустил.